baseurl = "https://statsjoke.me"
languageCode = "en-us"
disqusShortname = "bblstats"
title = "Home"
theme = "hugo-grapes"
enableEmoji = true

[permalinks]
  post = "/posts/:slug/"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 20

[params]
avatar = "img/grapes.svg"
mathjax = true
disqusURL= "https://statsjoke.me"
