baseurl = "https://statsjoke.me"
languageCode = "en-us"
disqusShortname = "bblstats"
googleAnalytics= "UA-154109734-1"
title = "Home"
theme = "hugo-grapes"
enableEmoji = true

[permalinks]
  post = "/posts/:slug/"

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "CV"
url = "/CV/"
weight = 2

[params]
avatar = "img/grapes.svg"
mathjax = true
disqusURL= "https://statsjoke.me"
